### ISSUE TITLE
Blinking

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#12]
Hey, top defender still seems to have blinking issues sometimes , especially when there's a higher number of players.

Also, could you add an option to disable money / damage dealt shown as a lot of communities have their own show damage plugins.

**Comment by darkerz7** [comment]
Disable money CVAR: sm_topdefenders_cashdiv 0. when using my plugin, other plugins showing damage are not needed. there is some kind of optimization since plugins showing damage calculate almost the same thing. Blinking is with regards to HUD messages at the end or messages in the center of the screen?

**Comment by asphyxious** [comment]
Blinking as in humans / zombie player models keep blinking with this plugin on, when there's a lot of players

**Comment by asphyxious** [comment]
And as for the cvar can you please add a cvar to disable damage dealt shown?

**Comment by darkerz7** [comment]
Added CVAR: sm_topdefenders_showdamage <0/1>. Removed the color of the skin. this should fix the blinking

**Comment by asphyxious** [comment]
Still happening
