### ISSUE TITLE
Eban issues

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#7]
Hey, seems like eban is bugged. My admins complained that they did !eban someone for 30 minutes , however they could still pickup items. Do I need to define a database or something?

**Comment by darkerz7** [comment]
strange, maybe a problem due to late loading from the database clientprefs. in fact, you can make it so that by default until the settings are loaded, the client will not be able to pick up an item, but honest players will suffer. can you describe in more detail under what circumstances a eban was not issued?

**Comment by asphyxious** [comment]
What is the default time for eban? Could you add a cvar to set time if a time is not mentioned? Eg if i do !eban darker , it should issue the time mentioned in cvar [0 would be permanent]

**Comment by darkerz7** [comment]
Added new cvar: entwatch_bantime
